import type { Location } from "@/types"

export const locations: Location[] = [
  {
    slug: "downtown-jacksonville",
    name: "Downtown Jacksonville",
    county: "Duval County",
    zipCodes: ["32202", "32204"],
    heading: "Locksmith in Downtown Jacksonville",
    description:
      "Emergency locksmith service in Downtown Jacksonville. Fast response for car lockouts, office lockouts, and residential emergencies near the riverfront.",
    landmarks: ["EverBank Stadium", "Jacksonville Landing", "Duval County Courthouse", "Main Street Bridge"],
    lat: 30.3322,
    lng: -81.6557,
    nearbyAreas: ["san-marco", "riverside", "arlington"],
    relatedPosts: ["how-fast-can-emergency-locksmiths-arrive", "what-to-do-when-locked-out-of-car-jacksonville"],
  },
  {
    slug: "san-marco",
    name: "San Marco",
    county: "Duval County",
    zipCodes: ["32207"],
    heading: "Locksmith in San Marco Jacksonville",
    description:
      "Mobile locksmith serving San Marco and surrounding neighborhoods. Quick response for home lockouts, rekeying, and car key replacement.",
    landmarks: ["San Marco Square", "Memorial Park", "Hendricks Avenue"],
    lat: 30.3067,
    lng: -81.6533,
    nearbyAreas: ["downtown-jacksonville", "riverside", "southside"],
    relatedPosts: ["how-much-does-rekeying-cost", "should-you-rekey-or-replace-locks"],
  },
  {
    slug: "southside",
    name: "Southside Jacksonville",
    county: "Duval County",
    zipCodes: ["32216", "32256", "32258"],
    heading: "Locksmith in Southside Jacksonville",
    description:
      "24/7 mobile locksmith serving Southside Jacksonville including Baymeadows, Deerwood, and the Town Center area.",
    landmarks: ["St. Johns Town Center", "Baymeadows Road", "I-95 Southside"],
    lat: 30.2370,
    lng: -81.5993,
    nearbyAreas: ["san-marco", "mandarin", "arlington"],
    relatedPosts: ["should-you-rekey-or-replace-locks", "best-smart-locks-for-florida-homes"],
  },
  {
    slug: "arlington",
    name: "Arlington",
    county: "Duval County",
    zipCodes: ["32211", "32277"],
    heading: "Locksmith in Arlington Jacksonville",
    description:
      "Emergency locksmith in Arlington serving Fort Caroline, Regency, and surrounding neighborhoods with fast 24/7 response.",
    landmarks: ["Regency Square", "Fort Caroline Road", "Arlington Expressway"],
    lat: 30.3458,
    lng: -81.5692,
    nearbyAreas: ["downtown-jacksonville", "southside", "neptune-beach"],
    relatedPosts: ["how-fast-can-emergency-locksmiths-arrive", "what-to-do-when-locked-out-of-car-jacksonville"],
  },
  {
    slug: "riverside",
    name: "Riverside",
    county: "Duval County",
    zipCodes: ["32204"],
    heading: "Locksmith in Riverside Jacksonville",
    description:
      "Local locksmith in Riverside, Jacksonville. Serving Avondale, Five Points, and the historic Riverside neighborhood with full mobile service.",
    landmarks: ["Five Points", "Cummer Museum", "Riverside Arts Market"],
    lat: 30.3192,
    lng: -81.6751,
    nearbyAreas: ["downtown-jacksonville", "san-marco"],
    relatedPosts: ["how-much-does-rekeying-cost", "should-you-rekey-or-replace-locks"],
  },
  {
    slug: "mandarin",
    name: "Mandarin",
    county: "Duval County",
    zipCodes: ["32257", "32223"],
    heading: "Locksmith in Mandarin Jacksonville",
    description:
      "Mobile locksmith serving Mandarin and surrounding St. Johns County border areas. Fast response for lockouts and key replacement.",
    landmarks: ["Mandarin Road", "Julington Creek", "Walter Jones Historical Park"],
    lat: 30.1728,
    lng: -81.5982,
    nearbyAreas: ["southside", "orange-park"],
    relatedPosts: ["how-much-does-rekeying-cost", "best-smart-locks-for-florida-homes"],
  },
  {
    slug: "neptune-beach",
    name: "Neptune Beach",
    county: "Duval County",
    zipCodes: ["32266"],
    heading: "Locksmith in Neptune Beach FL",
    description:
      "Emergency locksmith serving Neptune Beach and Atlantic Beach. Fast response for car lockouts and home lockouts near the coast.",
    landmarks: ["Neptune Beach Town Center", "Atlantic Boulevard", "Neptune Beach Community Park"],
    lat: 30.3124,
    lng: -81.3924,
    nearbyAreas: ["jacksonville-beach", "arlington", "downtown-jacksonville"],
    relatedPosts: ["how-fast-can-emergency-locksmiths-arrive", "what-to-do-when-locked-out-of-car-jacksonville"],
  },
  {
    slug: "jacksonville-beach",
    name: "Jacksonville Beach",
    county: "Duval County",
    zipCodes: ["32250", "32240"],
    heading: "Locksmith in Jacksonville Beach FL",
    description:
      "24/7 mobile locksmith serving Jacksonville Beach, FL. Fast response for car lockouts, home lockouts, and key replacement along the Beaches corridor. Serving the Jacksonville Beach Pier area and surrounding neighborhoods.",
    landmarks: ["Jacksonville Beach Pier", "Beach Boulevard", "Pablo Historical Park", "3rd Street"],
    lat: 30.2786,
    lng: -81.3936,
    nearbyAreas: ["neptune-beach", "arlington", "downtown-jacksonville"],
    relatedPosts: ["what-to-do-when-locked-out-of-car-jacksonville", "how-fast-can-emergency-locksmiths-arrive"],
  },
  {
    slug: "orange-park",
    name: "Orange Park",
    county: "Clay County",
    zipCodes: ["32073", "32065"],
    heading: "Locksmith in Orange Park FL",
    description:
      "Locksmith serving Orange Park and Clay County. Emergency lockouts, rekeying, and car key replacement near the Blanding Boulevard corridor.",
    landmarks: ["Orange Park Mall", "Blanding Boulevard", "I-295"],
    lat: 30.1652,
    lng: -81.7076,
    nearbyAreas: ["mandarin", "southside"],
    relatedPosts: ["how-much-does-rekeying-cost", "should-you-rekey-or-replace-locks"],
  },
]
